# Generated by Django 5.2.6 on 2025-12-31 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="DONE", max_length=20)),
                ("error_msg", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DetectItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("filename", models.CharField(max_length=255)),
                ("upload_path", models.CharField(max_length=500)),
                ("crack_prob", models.FloatField(blank=True, null=True)),
                ("inactive_prob", models.FloatField(blank=True, null=True)),
                ("is_bad", models.BooleanField(default=False)),
                (
                    "mask_label_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "overlay_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="detector.detectjob",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="detector_de_created_39acbe_idx"
                    ),
                    models.Index(
                        fields=["is_bad"], name="detector_de_is_bad_3d18c0_idx"
                    ),
                ],
            },
        ),
    ]
